In [ ]:
pip install numpy

In [3]:
import numpy as np
import pandas as pd


In [ ]:
#Crete a numpy array
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [ ]:
#create a pandas dataframe
data_frame = pd.DataFrame({'Name:':['A','B','C'], 'Age: ':[1,2,3]})
data_frame

Name:  Age: 
0     A      1
1     B      2
2     C      3

In [ ]:
#Create array of random integers
arr= np.random.randint(0,100, size=10)
arr

array([22, 39, 62, 82, 46, 60, 64, 78, 17, 28])

In [ ]:
#sort array in ascending order
arr_sort = np.sort(arr)


array([ 2,  6, 11, 13, 15, 23, 27, 29, 33, 51])

In [ ]:
#One Dimensional array
arr = np.array([1,2,3,4,5,6])
# lets pu an operation on it
# lets square it by 2
sqr_arr = arr**2
print(sqr_arr)

[ 1  4  9 16 25 36]


In [ ]:
# Here we see in one go we are able to apply the operation to teh rest of the elements in the array
#Similarly
sum_arr = np.sum(arr) # like this add all the elements in the array
print(sum_arr)

21


In [ ]:
#Similarly, we use mean to find the mean of the elements
mean_arr = np.mean(arr)
mean_arr

3.5

In [ ]:
#Why is Numpy important in data Analysis?
#1 we can make oneD or 2D or any Dimention arrays in Numpy
#Example of one d is above, lets make 2D array
arr_2d = np.array([[1,2,3],[4,10,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#2 Numpy Mean
#It is a statistical method, Provides measure of the central tendancy of a dataset
mean_arr_2d = np.mean(arr_2d)
mean_arr_2d

5.555555555555555

In [ ]:
#Numpy Meadian, This is also for central tendancy
median_arr_2d = np.median(arr_2d)
median_arr_2d

5.0

In [ ]:
#numpy std;calculate standard deviation of an array
#measure of spread or variability of a dataset
std_arr_2d = np.std(arr_2d)
std_arr_2d

2.581988897471611

In [ ]:
#lets do it simple
arr = np.array([1,2,3,4,5])
np.std(arr)

1.4142135623730951

In [ ]:
#Numpy functionality
#1 Numpy Array
#Howw? np.array([1,2,3])


In [ ]:
#2 is Numpy arange
#used to create an array with evenly spaced values within a specified range
#takes 3 arguments start stop step
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(5,10,2)
arr

array([5, 7, 9])

In [ ]:
#Numpy Linespace
#Evenly spaced values within a specified range, start stop num
arr = np.linspace(0,1,100)
arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
#Numpy reshape: used to change the shap eof an array
#for example we make an array using arange function in numpy
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#the above array is a one dimentional array and we want to change the shape and turn into a 2 dimentional array
arr_2d = arr.reshape(2,5)
arr_2d
#Here we have a 5x2 matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#Numpy tranpose, you might have used this term while studying matrix
#what is a transpose?
#it simply means swapping rows and columns
new_arr = np.transpose(arr_2d)
new_arr
#here we get a 2x5 matrix

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
#Flatten is a method to convert multi dimentional array into a one dimentional array
arr_2d
new_arr = arr_2d.flatten()
new_arr
print(f'''Orginal array: {arr_2d} and new array {new_arr}''')

Orginal array: [[0 1 2 3 4]
 [5 6 7 8 9]] and new array [0 1 2 3 4 5 6 7 8 9]


In [4]:
#Indexing and slicing a numpy array
#extracting a subset of numpy array
#lets make a 3 dimentional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#Slice first matrix of array
#print(arr[0,::]) #here we mean 0th row will all elements in it
print(arr[0:,0:1])
#this is the code for slicing first column of the 2s matrix
print(arr[0:1])
#this is for first row

[[1]
 [4]
 [7]]
[[1 2 3]]


In [35]:
#for second column and third
print(arr[0:,1:2])
#second row
print(arr[1:2]) # here 1 is the second row and 0,1,2 elements in the second row

[[2]
 [5]
 [8]]
[[4 5 6]]


In [33]:
#for third column
print(arr[0:,2:])
print(arr[2:])

[[3]
 [6]
 [9]]
[[7 8 9]]


PANDAS


In [ ]:
#Pandas is a library built on top of numpy that provide data manipulation
#Designed to work with tabular data
#Provide 2 data types: 1) Series: One Dimension array with labels 2) DataFrame: two dimnesion with rows and columns


In [ ]:
#DATAFRAME AND DATA SETS
#Data Frame: Tabular data structure used to store data in rows and columns
#DataSet: collection of data used for analysis,modlling.dataset can be structured in diffrent ways


In [ ]:
#Data Types: Structured; Unstructured; SemiStructured
#Structured: Organised data into specific way
#example; RDBMS--> Data into tables and relation between those tables
#UnStructured: Does not have a specific structure
#example;textdata--> emails,posts; photos,audio
#SemiStr: some structurebut not fully organised
#example; Json,xml

In [40]:
#Lets create our first data frame in pandas
arr_2d = np.random.randint(4,6,(3,4)) # in range ig 4-6 we want number in a 3x4 matrix
arr_2d

array([[4, 5, 5, 5],
       [5, 4, 4, 5],
       [4, 4, 4, 4]])

In [45]:
first_dataframe = pd.DataFrame(arr_2d, columns = ['A','B','C','D'])
first_dataframe

A  B  C  D
0  4  5  5  5
1  5  4  4  5
2  4  4  4  4

In [48]:
#here the index has itself been set to 0,1,2
#now we want to change the index also
first_dataframe = pd.DataFrame(arr_2d, columns =['a','b','c','d'], index = ['first','seconnd','third'])
first_dataframe
#so here we see we changed the index also

a  b  c  d
first    4  5  5  5
seconnd  5  4  4  5
third    4  4  4  4

In [53]:
# Now we see we have data in a list and we want to be reporesented in the form of panda data frame
my_list = [['Apple', 10], ['Banana', 5], ['Avacado', 2],['Pineapple',15]] # this is a list of lists
# inthis list we have the fruit name and the quantity available
fruit_df = pd.DataFrame(my_list, columns = ['Fruits', 'Quantity'])
fruit_df


Fruits  Quantity
0      Apple        10
1     Banana         5
2    Avacado         2
3  Pineapple        15

In [56]:
#similarly if we use a dictionary
my_dict = {'Employee Name':['a','b','c'], 'Income': [1,2,3]}
my_dict_df = pd.DataFrame(my_dict)
my_dict_df

Employee Name  Income
0             a       1
1             b       2
2             c       3

In [64]:
# how use series in data frame
my_series = {'first_series' : pd.Series([1,2,3,4,5]), 'second_series':pd.Series([6,7,8,9,10])}
df = pd.DataFrame(my_series)
df

first_series  second_series
0             1              6
1             2              7
2             3              8
3             4              9
4             5             10

In [65]:
#when we have  alist of dictionaries
my_dict = [{'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}]
pd.DataFrame(my_dict) # it automatically identifies the key value pair and assigns them in the row column format

a   b   c
0   1   2   3
1  10  20  30

In [66]:
#lets see if key value pairs are not name: means we dont have a in first list
my_dict = [{'b':2,'c':3},{'a':10,'b':20,'c':30}]
pd.DataFrame(my_dict) it #gives NaN

b   c     a
0   2   3   NaN
1  20  30  10.0

In [84]:
#Other way when we have two lists
my_list1 = ['a','b','c']
my_list2 = [1,2,3]
#first we get them into a pair, How we do it by zipping it
#zip will change them into a tuple
my_tuple = list(zip(my_list1,my_list2)) # lets store the value in a variable
df = pd.DataFrame(my_tuple, columns = ['Name','Age'])
df

Name  Age
0    a    1
1    b    2
2    c    3

In [81]:
my_tuple # this the location where it is stored lets display it

In [82]:
list(my_tuple) # here we have changed it into a list with tuples inside:

[]

In [83]:
#Assign it in a varaiable
new_tuple = list(my_tuple)

In [79]:
#Now put them into a pamnda dataframe
df = pd.DataFrame(my_tuple, columns = ['Name','Age'])
df

Empty DataFrame
Columns: [Name, Age]
Index: []

In [ ]:
#here we did not get any data in the table the we executed the dataframe where we zipped the lists and it went well


In [91]:
#Now lets acccess our google drive to fetch data from it
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#'/contentdrive/drive/Mydrive/Foldername/Filename'

In [93]:
path = '/content/drive/MyDrive/Datasets/imdb_data.csv'
imdb_df = pd.read_csv(path)


In [94]:
imdb_df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [96]:
imdb_df.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   
4                                NaN  tt1380152                ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
4       2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   
4  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  
3  [{'credit_id': '52fe48779251

In [97]:
imdb_df.tail()

id belongs_to_collection    budget  \
2995  2996                   NaN         0   
2996  2997                   NaN         0   
2997  2998                   NaN  65000000   
2998  2999                   NaN  42000000   
2999  3000                   NaN  35000000   

                                                 genres  \
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                              homepage    imdb_id original_language  \
2995                               NaN  tt0109403                en   
2996                               NaN  tt2364975                sv   
2997                               NaN  tt0116908                en   
2998    http://www.alongcamepolly.com/  tt0343135                en   
2999  http://www.abductionthefilm.com/  tt1600195                en   

               original_title  \
2995                  Chasers   
2996              Vi är bäst!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               overview  popularity  ...  \
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date runtime                          spoken_languages    status  \
2995      4/22/94   102.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2996      3/28/13   102.0  [{'iso_639_1': 'sv', 'name': 'svenska'}]  Released   
2997     10/11/96   120.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2998      1/16/04    90.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2999      9/22/11   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                                tagline  \
2995  It was supposed to be a routine prisoner trans...   
2996                                                NaN   
2997               What's forgotten is not always gone.   
2998  For the most cautious man on Earth, life is ab...   
2999          They stole his life. He's taking it back.   

                        title  \
2995                  Chasers   
2996         We Are the Best!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               Keywords  \
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...   
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...   
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...   
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...   
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...   

                                                   cast  \
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...   
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...   
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...   
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...   
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew    revenue  
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687  
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590  
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761  
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155  

[5 rows x 23 columns]

In [101]:
imdb_df.head(2)

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   

                                              genres homepage    imdb_id  \
0                     [{'id': 35, 'name': 'Comedy'}]      NaN  tt2637294   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN  tt0368933   

  original_language                            original_title  \
0                en                    Hot Tub Time Machine 2   
1                en  The Princess Diaries 2: Royal Engagement   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   

  release_date runtime                          spoken_languages    status  \
0      2/20/15    93.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1       8/6/04   113.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline  \
0  The Laws of Space and Time are About to be Vio...   
1  It can take a lifetime to find true love; she'...   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  

[2 rows x 23 columns]

In [110]:
list(imdb_df.columns)

['id',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'Keywords',
 'cast',
 'crew',
 'revenue']

In [109]:
new_df = imdb_df[['id','budget', 'title','revenue']]
new_df
new_df.head()

id    budget                                     title   revenue
0   1  14000000                    Hot Tub Time Machine 2  12314651
1   2  40000000  The Princess Diaries 2: Royal Engagement  95149435
2   3   3300000                                  Whiplash  13092000
3   4   1200000                                   Kahaani  16000000
4   5         0                                Marine Boy   3923970

In [113]:
#You work for a company that sells fruits and vegetables.
#Your boss wants to know the average price and total sales of all the fruits they sold last month.
#Your task is to analyze the data and provide the required information.
fruits = np.array(["Apple", "Banana", "Cherry", "Dragonfruit", "Elderberry"])
quantity_sold = np.array([100, 200, 50, 75, 150])
price_per_unit = np.array([0.5, 0.25, 1, 1.5, 2])


In [119]:
average_price = np.mean(price_per_unit)
total_sale = np.sum(quantity_sold * price_per_unit)
print(f"Average price = {average_price} and Total sale = {total_sale}")



Average price = 1.05 and Total sale = 562.5


In [124]:
#Put all this in a panda dataframe
my_tuple = pd.DataFrame(list(zip(fruits,quantity_sold,price_per_unit)))
my_tuple

0    1     2
0        Apple  100  0.50
1       Banana  200  0.25
2       Cherry   50  1.00
3  Dragonfruit   75  1.50
4   Elderberry  150  2.00

In [137]:
#You work for a company that sells various products. Your boss wants to know some
#statistical information about the sales of the products. Your task is to analyze the data and provide the required information:

#Mean sales.
#Median sales.
#Mode of Sales.
#Standard Deviation.
#Variance.
from scipy import stats
sales = np.array([100, 200, 150, 75, 250, 300, 175, 225, 125, 275])
print(f"Mean of Sales = {np.mean(sales)}")
print(f"Median Sales = {np.median(sales)}")
print(f"Mode Sales = {np.argmax(np.bincount(sales))}")
print(f"Mode Sales using python library scipy = {stats.mode(sales)}")
print(f"STD = {np.std(sales)}")
print(f"Varience = {np.var(sales)}")

Mean of Sales = 187.5
Median Sales = 187.5
Mode Sales = 75
Mode Sales using python library scipy = ModeResult(mode=75, count=1)
STD = 71.80703308172536
Varience = 5156.25


In [156]:
#Create a 2D array representing the chip design, where each row represents a
#layer of the chip and each column represents a feature of the layer.
#The values in the array should range from 0 to 255 and be evenly spaced.
arr = np.linspace(0,255,(4*6)).reshape(4,6)
arr
round = np.round(arr,2) #this is how we round in numpy
round

array([[  0.  ,  11.09,  22.17,  33.26,  44.35,  55.43],
       [ 66.52,  77.61,  88.7 ,  99.78, 110.87, 121.96],
       [133.04, 144.13, 155.22, 166.3 , 177.39, 188.48],
       [199.57, 210.65, 221.74, 232.83, 243.91, 255.  ]])

In [166]:
#Import the pandas library
import pandas as pd

#Create a dictionary that contains the data for the dataframe
data = {'Product': ['Shirts', 'Pants', 'Jackets', 'Shoes'],
        'Sales': [100, 75, 50, 25]}
#Convert the dictionary into a Pandas dataframe
df = pd.DataFrame(data)
#Print the dataframe to verify that it was created correctly
df
#Calculate the average sales


Product  Sales
0   Shirts    100
1    Pants     75
2  Jackets     50
3    Shoes     25

In [172]:
average_sale = df['Sales'].mean()
print(f"Average sale is {average_sale}")


Average sale is 62.5


In [174]:
books_dict = {
    'Title': ['Book A', 'Book B', 'Book C', 'Book D', 'Book E'],
    'Author': ['Author X', 'Author Y', 'Author X', 'Author Z', 'Author Y'],
    'Year of Publication': [2005, 2010, 2002, 2015, 2018],
    'Number of Pages': [300, 250, 180, 400, 320]
}
#Print the first five rows of the DataFrame.
#Print the last three rows of the DataFrame.
#Sort the DataFrame by year of publication in ascending order.
#Sort the DataFrame by number of pages in descending order.
#Filter the DataFrame to show only books published after the year 2000.
#Calculate the average number of pages for all books in the DataFrame.
#Group the DataFrame by author, and calculate the total number of pages for each author.

In [200]:
df = pd.DataFrame(books_dict)
df

Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [178]:
df.head()

Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [179]:
df.tail(3)

Title    Author  Year of Publication  Number of Pages
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [183]:
df.sort_values(by= 'Year of Publication')

Title    Author  Year of Publication  Number of Pages
2  Book C  Author X                 2002              180
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [184]:
df.sort_values(by= 'Number of Pages', ascending = False)

Title    Author  Year of Publication  Number of Pages
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180

In [186]:
#Filter the DataFrame to show only books published after the year 2000.
df[df['Year of Publication'] > 2015 ]

Title    Author  Year of Publication  Number of Pages
4  Book E  Author Y                 2018              320

In [187]:
#Calculate the average number of pages for all books in the DataFrame.
df['Number of Pages'].mean()

290.0

In [206]:
#Group the DataFrame by author, and calculate the total number of pages for each author.
#print(df)
a = df.groupby('Author')['Number of Pages'].sum()
a


Author
Author X    480
Author Y    570
Author Z    400
Name: Number of Pages, dtype: int64