In [ ]:
pip install numpy

In [3]:
import numpy as np
import pandas as pd


In [ ]:
#Crete a numpy array
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [ ]:
#create a pandas dataframe
data_frame = pd.DataFrame({'Name:':['A','B','C'], 'Age: ':[1,2,3]})
data_frame

Name:  Age: 
0     A      1
1     B      2
2     C      3

In [ ]:
#Create array of random integers
arr= np.random.randint(0,100, size=10)
arr

array([22, 39, 62, 82, 46, 60, 64, 78, 17, 28])

In [ ]:
#sort array in ascending order
arr_sort = np.sort(arr)


array([ 2,  6, 11, 13, 15, 23, 27, 29, 33, 51])

In [ ]:
#One Dimensional array
arr = np.array([1,2,3,4,5,6])
# lets pu an operation on it
# lets square it by 2
sqr_arr = arr**2
print(sqr_arr)

[ 1  4  9 16 25 36]


In [ ]:
# Here we see in one go we are able to apply the operation to teh rest of the elements in the array
#Similarly
sum_arr = np.sum(arr) # like this add all the elements in the array
print(sum_arr)

21


In [ ]:
#Similarly, we use mean to find the mean of the elements
mean_arr = np.mean(arr)
mean_arr

3.5

In [ ]:
#Why is Numpy important in data Analysis?
#1 we can make oneD or 2D or any Dimention arrays in Numpy
#Example of one d is above, lets make 2D array
arr_2d = np.array([[1,2,3],[4,10,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#2 Numpy Mean
#It is a statistical method, Provides measure of the central tendancy of a dataset
mean_arr_2d = np.mean(arr_2d)
mean_arr_2d

5.555555555555555

In [ ]:
#Numpy Meadian, This is also for central tendancy
median_arr_2d = np.median(arr_2d)
median_arr_2d

5.0

In [ ]:
#numpy std;calculate standard deviation of an array
#measure of spread or variability of a dataset
std_arr_2d = np.std(arr_2d)
std_arr_2d

2.581988897471611

In [ ]:
#lets do it simple
arr = np.array([1,2,3,4,5])
np.std(arr)

1.4142135623730951

In [ ]:
#Numpy functionality
#1 Numpy Array
#Howw? np.array([1,2,3])


In [ ]:
#2 is Numpy arange
#used to create an array with evenly spaced values within a specified range
#takes 3 arguments start stop step
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(5,10,2)
arr

array([5, 7, 9])

In [ ]:
#Numpy Linespace
#Evenly spaced values within a specified range, start stop num
arr = np.linspace(0,1,100)
arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
#Numpy reshape: used to change the shap eof an array
#for example we make an array using arange function in numpy
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#the above array is a one dimentional array and we want to change the shape and turn into a 2 dimentional array
arr_2d = arr.reshape(2,5)
arr_2d
#Here we have a 5x2 matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#Numpy tranpose, you might have used this term while studying matrix
#what is a transpose?
#it simply means swapping rows and columns
new_arr = np.transpose(arr_2d)
new_arr
#here we get a 2x5 matrix

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
#Flatten is a method to convert multi dimentional array into a one dimentional array
arr_2d
new_arr = arr_2d.flatten()
new_arr
print(f'''Orginal array: {arr_2d} and new array {new_arr}''')

Orginal array: [[0 1 2 3 4]
 [5 6 7 8 9]] and new array [0 1 2 3 4 5 6 7 8 9]


In [4]:
#Indexing and slicing a numpy array
#extracting a subset of numpy array
#lets make a 3 dimentional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#Slice first matrix of array
#print(arr[0,::]) #here we mean 0th row will all elements in it
print(arr[0:,0:1])
#this is the code for slicing first column of the 2s matrix
print(arr[0:1])
#this is for first row

[[1]
 [4]
 [7]]
[[1 2 3]]


In [35]:
#for second column and third
print(arr[0:,1:2])
#second row
print(arr[1:2]) # here 1 is the second row and 0,1,2 elements in the second row

[[2]
 [5]
 [8]]
[[4 5 6]]


In [33]:
#for third column
print(arr[0:,2:])
print(arr[2:])

[[3]
 [6]
 [9]]
[[7 8 9]]


PANDAS


In [ ]:
#Pandas is a library built on top of numpy that provide data manipulation
#Designed to work with tabular data
#Provide 2 data types: 1) Series: One Dimension array with labels 2) DataFrame: two dimnesion with rows and columns


In [ ]:
#DATAFRAME AND DATA SETS
#Data Frame: Tabular data structure used to store data in rows and columns
#DataSet: collection of data used for analysis,modlling.dataset can be structured in diffrent ways


In [ ]:
#Data Types: Structured; Unstructured; SemiStructured
#Structured: Organised data into specific way
#example; RDBMS--> Data into tables and relation between those tables
#UnStructured: Does not have a specific structure
#example;textdata--> emails,posts; photos,audio
#SemiStr: some structurebut not fully organised
#example; Json,xml

In [40]:
#Lets create our first data frame in pandas
arr_2d = np.random.randint(4,6,(3,4)) # in range ig 4-6 we want number in a 3x4 matrix
arr_2d

array([[4, 5, 5, 5],
       [5, 4, 4, 5],
       [4, 4, 4, 4]])

In [45]:
first_dataframe = pd.DataFrame(arr_2d, columns = ['A','B','C','D'])
first_dataframe

A  B  C  D
0  4  5  5  5
1  5  4  4  5
2  4  4  4  4

In [48]:
#here the index has itself been set to 0,1,2
#now we want to change the index also
first_dataframe = pd.DataFrame(arr_2d, columns =['a','b','c','d'], index = ['first','seconnd','third'])
first_dataframe
#so here we see we changed the index also

a  b  c  d
first    4  5  5  5
seconnd  5  4  4  5
third    4  4  4  4

In [53]:
# Now we see we have data in a list and we want to be reporesented in the form of panda data frame
my_list = [['Apple', 10], ['Banana', 5], ['Avacado', 2],['Pineapple',15]] # this is a list of lists
# inthis list we have the fruit name and the quantity available
fruit_df = pd.DataFrame(my_list, columns = ['Fruits', 'Quantity'])
fruit_df


Fruits  Quantity
0      Apple        10
1     Banana         5
2    Avacado         2
3  Pineapple        15

In [56]:
#similarly if we use a dictionary
my_dict = {'Employee Name':['a','b','c'], 'Income': [1,2,3]}
my_dict_df = pd.DataFrame(my_dict)
my_dict_df

Employee Name  Income
0             a       1
1             b       2
2             c       3

In [64]:
# how use series in data frame
my_series = {'first_series' : pd.Series([1,2,3,4,5]), 'second_series':pd.Series([6,7,8,9,10])}
df = pd.DataFrame(my_series)
df

first_series  second_series
0             1              6
1             2              7
2             3              8
3             4              9
4             5             10

In [65]:
#when we have  alist of dictionaries
my_dict = [{'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}]
pd.DataFrame(my_dict) # it automatically identifies the key value pair and assigns them in the row column format

a   b   c
0   1   2   3
1  10  20  30

In [66]:
#lets see if key value pairs are not name: means we dont have a in first list
my_dict = [{'b':2,'c':3},{'a':10,'b':20,'c':30}]
pd.DataFrame(my_dict) it #gives NaN

b   c     a
0   2   3   NaN
1  20  30  10.0

In [84]:
#Other way when we have two lists
my_list1 = ['a','b','c']
my_list2 = [1,2,3]
#first we get them into a pair, How we do it by zipping it
#zip will change them into a tuple
my_tuple = list(zip(my_list1,my_list2)) # lets store the value in a variable
df = pd.DataFrame(my_tuple, columns = ['Name','Age'])
df

Name  Age
0    a    1
1    b    2
2    c    3

In [81]:
my_tuple # this the location where it is stored lets display it

In [82]:
list(my_tuple) # here we have changed it into a list with tuples inside:

[]

In [83]:
#Assign it in a varaiable
new_tuple = list(my_tuple)

In [79]:
#Now put them into a pamnda dataframe
df = pd.DataFrame(my_tuple, columns = ['Name','Age'])
df

Empty DataFrame
Columns: [Name, Age]
Index: []

In [ ]:
#here we did not get any data in the table the we executed the dataframe where we zipped the lists and it went well


In [1]:
#Now lets acccess our google drive to fetch data from it
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#'/contentdrive/drive/Mydrive/Foldername/Filename'

In [3]:
import pandas as pd

In [4]:
path = '/content/drive/MyDrive/Datasets/imdb_data.csv'
imdb_df = pd.read_csv(path)


In [5]:
imdb_df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [96]:
imdb_df.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id original_language  \
0                                NaN  tt2637294                en   
1                                NaN  tt0368933                en   
2  http://sonyclassics.com/whiplash/  tt2582802                en   
3         http://kahaanithefilm.com/  tt1821480                hi   
4                                NaN  tt1380152                ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

  release_date runtime                                   spoken_languages  \
0      2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1       8/6/04   113.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2     10/10/14   105.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3       3/9/12   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
4       2/5/09   118.0           [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   
4  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000  
3  [{'credit_id': '52fe48779251

In [97]:
imdb_df.tail()

id belongs_to_collection    budget  \
2995  2996                   NaN         0   
2996  2997                   NaN         0   
2997  2998                   NaN  65000000   
2998  2999                   NaN  42000000   
2999  3000                   NaN  35000000   

                                                 genres  \
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                              homepage    imdb_id original_language  \
2995                               NaN  tt0109403                en   
2996                               NaN  tt2364975                sv   
2997                               NaN  tt0116908                en   
2998    http://www.alongcamepolly.com/  tt0343135                en   
2999  http://www.abductionthefilm.com/  tt1600195                en   

               original_title  \
2995                  Chasers   
2996              Vi är bäst!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               overview  popularity  ...  \
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date runtime                          spoken_languages    status  \
2995      4/22/94   102.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2996      3/28/13   102.0  [{'iso_639_1': 'sv', 'name': 'svenska'}]  Released   
2997     10/11/96   120.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2998      1/16/04    90.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2999      9/22/11   106.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                                tagline  \
2995  It was supposed to be a routine prisoner trans...   
2996                                                NaN   
2997               What's forgotten is not always gone.   
2998  For the most cautious man on Earth, life is ab...   
2999          They stole his life. He's taking it back.   

                        title  \
2995                  Chasers   
2996         We Are the Best!   
2997  The Long Kiss Goodnight   
2998         Along Came Polly   
2999                Abduction   

                                               Keywords  \
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...   
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...   
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...   
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...   
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...   

                                                   cast  \
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...   
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...   
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...   
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...   
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew    revenue  
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687  
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590  
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761  
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155  

[5 rows x 23 columns]

In [101]:
imdb_df.head(2)

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   

                                              genres homepage    imdb_id  \
0                     [{'id': 35, 'name': 'Comedy'}]      NaN  tt2637294   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN  tt0368933   

  original_language                            original_title  \
0                en                    Hot Tub Time Machine 2   
1                en  The Princess Diaries 2: Royal Engagement   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   

  release_date runtime                          spoken_languages    status  \
0      2/20/15    93.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1       8/6/04   113.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline  \
0  The Laws of Space and Time are About to be Vio...   
1  It can take a lifetime to find true love; she'...   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435  

[2 rows x 23 columns]

In [110]:
list(imdb_df.columns)

['id',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'Keywords',
 'cast',
 'crew',
 'revenue']

In [109]:
new_df = imdb_df[['id','budget', 'title','revenue']]
new_df
new_df.head()

id    budget                                     title   revenue
0   1  14000000                    Hot Tub Time Machine 2  12314651
1   2  40000000  The Princess Diaries 2: Royal Engagement  95149435
2   3   3300000                                  Whiplash  13092000
3   4   1200000                                   Kahaani  16000000
4   5         0                                Marine Boy   3923970

In [113]:
#You work for a company that sells fruits and vegetables.
#Your boss wants to know the average price and total sales of all the fruits they sold last month.
#Your task is to analyze the data and provide the required information.
fruits = np.array(["Apple", "Banana", "Cherry", "Dragonfruit", "Elderberry"])
quantity_sold = np.array([100, 200, 50, 75, 150])
price_per_unit = np.array([0.5, 0.25, 1, 1.5, 2])


In [119]:
average_price = np.mean(price_per_unit)
total_sale = np.sum(quantity_sold * price_per_unit)
print(f"Average price = {average_price} and Total sale = {total_sale}")



Average price = 1.05 and Total sale = 562.5


In [124]:
#Put all this in a panda dataframe
my_tuple = pd.DataFrame(list(zip(fruits,quantity_sold,price_per_unit)))
my_tuple

0    1     2
0        Apple  100  0.50
1       Banana  200  0.25
2       Cherry   50  1.00
3  Dragonfruit   75  1.50
4   Elderberry  150  2.00

In [137]:
#You work for a company that sells various products. Your boss wants to know some
#statistical information about the sales of the products. Your task is to analyze the data and provide the required information:

#Mean sales.
#Median sales.
#Mode of Sales.
#Standard Deviation.
#Variance.
from scipy import stats
sales = np.array([100, 200, 150, 75, 250, 300, 175, 225, 125, 275])
print(f"Mean of Sales = {np.mean(sales)}")
print(f"Median Sales = {np.median(sales)}")
print(f"Mode Sales = {np.argmax(np.bincount(sales))}")
print(f"Mode Sales using python library scipy = {stats.mode(sales)}")
print(f"STD = {np.std(sales)}")
print(f"Varience = {np.var(sales)}")

Mean of Sales = 187.5
Median Sales = 187.5
Mode Sales = 75
Mode Sales using python library scipy = ModeResult(mode=75, count=1)
STD = 71.80703308172536
Varience = 5156.25


In [156]:
#Create a 2D array representing the chip design, where each row represents a
#layer of the chip and each column represents a feature of the layer.
#The values in the array should range from 0 to 255 and be evenly spaced.
arr = np.linspace(0,255,(4*6)).reshape(4,6)
arr
round = np.round(arr,2) #this is how we round in numpy
round

array([[  0.  ,  11.09,  22.17,  33.26,  44.35,  55.43],
       [ 66.52,  77.61,  88.7 ,  99.78, 110.87, 121.96],
       [133.04, 144.13, 155.22, 166.3 , 177.39, 188.48],
       [199.57, 210.65, 221.74, 232.83, 243.91, 255.  ]])

In [166]:
#Import the pandas library
import pandas as pd

#Create a dictionary that contains the data for the dataframe
data = {'Product': ['Shirts', 'Pants', 'Jackets', 'Shoes'],
        'Sales': [100, 75, 50, 25]}
#Convert the dictionary into a Pandas dataframe
df = pd.DataFrame(data)
#Print the dataframe to verify that it was created correctly
df
#Calculate the average sales


Product  Sales
0   Shirts    100
1    Pants     75
2  Jackets     50
3    Shoes     25

In [172]:
average_sale = df['Sales'].mean()
print(f"Average sale is {average_sale}")


Average sale is 62.5


In [174]:
books_dict = {
    'Title': ['Book A', 'Book B', 'Book C', 'Book D', 'Book E'],
    'Author': ['Author X', 'Author Y', 'Author X', 'Author Z', 'Author Y'],
    'Year of Publication': [2005, 2010, 2002, 2015, 2018],
    'Number of Pages': [300, 250, 180, 400, 320]
}
#Print the first five rows of the DataFrame.
#Print the last three rows of the DataFrame.
#Sort the DataFrame by year of publication in ascending order.
#Sort the DataFrame by number of pages in descending order.
#Filter the DataFrame to show only books published after the year 2000.
#Calculate the average number of pages for all books in the DataFrame.
#Group the DataFrame by author, and calculate the total number of pages for each author.

In [200]:
df = pd.DataFrame(books_dict)
df

Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [178]:
df.head()

Title    Author  Year of Publication  Number of Pages
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [179]:
df.tail(3)

Title    Author  Year of Publication  Number of Pages
2  Book C  Author X                 2002              180
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [183]:
df.sort_values(by= 'Year of Publication')

Title    Author  Year of Publication  Number of Pages
2  Book C  Author X                 2002              180
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320

In [184]:
df.sort_values(by= 'Number of Pages', ascending = False)

Title    Author  Year of Publication  Number of Pages
3  Book D  Author Z                 2015              400
4  Book E  Author Y                 2018              320
0  Book A  Author X                 2005              300
1  Book B  Author Y                 2010              250
2  Book C  Author X                 2002              180

In [186]:
#Filter the DataFrame to show only books published after the year 2000.
df[df['Year of Publication'] > 2015 ]

Title    Author  Year of Publication  Number of Pages
4  Book E  Author Y                 2018              320

In [187]:
#Calculate the average number of pages for all books in the DataFrame.
df['Number of Pages'].mean()

290.0

In [206]:
#Group the DataFrame by author, and calculate the total number of pages for each author.
#print(df)
a = df.groupby('Author')['Number of Pages'].sum()
a


Author
Author X    480
Author Y    570
Author Z    400
Name: Number of Pages, dtype: int64

In [6]:
imdb_df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [8]:
imdb_df.head(1)

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   

                           genres homepage    imdb_id original_language  \
0  [{'id': 35, 'name': 'Comedy'}]      NaN  tt2637294                en   

           original_title                                           overview  \
0  Hot Tub Time Machine 2  When Lou, who has become the "father of the In...   

   popularity  ... release_date runtime  \
0    6.575393  ...      2/20/15    93.0   

                           spoken_languages    status  \
0  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline                   title  \
0  The Laws of Space and Time are About to be Vio...  Hot Tub Time Machine 2   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   

                                                crew   revenue  
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651  

[1 rows x 23 columns]

In [9]:
imdb_df.tail(1)

id belongs_to_collection    budget  \
2999  3000                   NaN  35000000   

                                                 genres  \
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                              homepage    imdb_id original_language  \
2999  http://www.abductionthefilm.com/  tt1600195                en   

     original_title                                           overview  \
2999      Abduction  A young man sets out to uncover the truth abou...   

      popularity  ... release_date runtime  \
2999   10.512109  ...      9/22/11   106.0   

                              spoken_languages    status  \
2999  [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                        tagline      title  \
2999  They stole his life. He's taking it back.  Abduction   

                                               Keywords  \
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...   

                                                   cast  \
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...   

                                                   crew   revenue  
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...  82087155  

[1 rows x 23 columns]

In [10]:
imdb_df.info() # Info prints basic information about our data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     3000 non-null   int64  
 1   belongs_to_collection  604 non-null    object 
 2   budget                 3000 non-null   int64  
 3   genres                 2993 non-null   object 
 4   homepage               946 non-null    object 
 5   imdb_id                3000 non-null   object 
 6   original_language      3000 non-null   object 
 7   original_title         3000 non-null   object 
 8   overview               2992 non-null   object 
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object 
 11  production_companies   2844 non-null   object 
 12  production_countries   2945 non-null   object 
 13  release_date           3000 non-null   object 
 14  runtime                2998 non-null   float64
 15  spok

In [13]:
imdb_df.shape #This gives us the shape of the dataframe
#here it says that we have 3000 rows and 23 colums in thi sdata frame


(3000, 23)

In [22]:
# so if you want to change the name of any column in the data frame we use
#rename()
#first we see what all columns do we have
imdb_df.columns
#lets put it in alist for better visualisation
list(imdb_df.columns)
#now you want to change the name of any of the columns, suppose we want to change 'original_language'
#to "lang"
imdb_df.rename(columns = {'original_language': 'Lang'})
list(imdb_df.columns) # we see after again running the column list to check if change hads been made
#what do we see? no change in the original datframe
#if we put it in a variable and call that variable
df = imdb_df.rename(columns = {'original_language': 'Lang'})
#call the columns of this df now
df.columns
#we see a change there but if we want the change in the original data frame
#we use inplace = True
imdb_df.rename(columns = {'original_language': 'Lang'},inplace = True)
imdb_df.columns # see there  is a change in the original data frame

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'Lang', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [23]:
# Describe() returns the statistical value of the numeric columns
imdb_df.describe()

id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [27]:
working_path = '/content/drive/MyDrive/Datasets/'
imdb_df.to_csv(working_path + 'output_new.csv')
#here use .csv so that the file is readable in the drive

In [29]:
#To sort a values in column with respect to some column we use sort_value
imdb_df.sort_values('budget',ascending = False).head(3)
#here we used head to show us the top 3 highest budgets: ascending false is for descending

id                              belongs_to_collection     budget  \
2135  2136  [{'id': 295, 'name': 'Pirates of the Caribbean...  380000000   
2209  2210  [{'id': 295, 'name': 'Pirates of the Caribbean...  300000000   
2770  2771  [{'id': 86311, 'name': 'The Avengers Collectio...  280000000   

                                                 genres  \
2135  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...   
2209  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2770  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   

                                               homepage    imdb_id Lang  \
2135  http://disney.go.com/pirates/index-on-stranger...  tt1298650   en   
2209       http://disney.go.com/disneypictures/pirates/  tt0449088   en   
2770  http://marvel.com/movies/movie/193/avengers_ag...  tt2395427   en   

                                   original_title  \
2135  Pirates of the Caribbean: On Stranger Tides   
2209     Pirates of the Caribbean: At World's End   
2770                      Avengers: Age of Ultron   

                                               overview  popularity  ...  \
2135  Captain Jack Sparrow crosses paths with a woma...   27.887720  ...   
2209  Captain Barbossa, long believed to be dead, ha...   31.363664  ...   
2770  When Tony Stark tries to jumpstart a dormant p...   37.379420  ...   

     release_date runtime                                   spoken_languages  \
2135      5/14/11   136.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2209      5/19/07   169.0           [{'iso_639_1': 'en', 'name': 'English'}]   
2770      4/22/15   141.0           [{'iso_639_1': 'en', 'name': 'English'}]   

        status                                         tagline  \
2135  Released                     Live Forever Or Die Trying.   
2209  Released  At the end of the world, the adventure begins.   
2770  Released                             A New Age Has Come.   

                                            title  \
2135  Pirates of the Caribbean: On Stranger Tides   
2209     Pirates of the Caribbean: At World's End   
2770                      Avengers: Age of Ultron   

                                               Keywords  \
2135  [{'id': 658, 'name': 'sea'}, {'id': 1316, 'nam...   
2209  [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...   
2770  [{'id': 8828, 'name': 'marvel comic'}, {'id': ...   

                                                   cast  \
2135  [{'cast_id': 15, 'character': 'Captain Jack Sp...   
2209  [{'cast_id': 4, 'character': 'Captain Jack Spa...   
2770  [{'cast_id': 76, 'character': 'Tony Stark / Ir...   

                                                   crew     revenue  
2135  [{'credit_id': '566b4f54c3a3683f56005151', 'de...  1045713802  
2209  [{'credit_id': '52fe4232c3a36847f800b579', 'de...   961000000  
2770  [{'credit_id': '55d5f7d4c3a3683e7e0016eb', 'de...  1405403694  

[3 rows x 23 columns]

In [44]:
#Indexing and slicing in Pandas
#Indexing means we want a singl eelement
#Slicing means we want a portion after using a range of index
# 1) loc (Locationing)
#imdb_df.loc[1,['budget','Lang','overview']]
#here we say 1st row and these colums in that row
imdb_df.loc[1:5,['budget','Lang','overview']]
#here we slice it by using 1:5 here rows from 1 to 5 are shown 5 included
imdb_df.loc[50:60,['budget','genres','runtime']]
imdb_df.loc[:,['budget','genres','runtime']]

budget                                             genres  runtime
0  14000000                     [{'id': 35, 'name': 'Comedy'}]     93.0
1  40000000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    113.0
2   3300000                      [{'id': 18, 'name': 'Drama'}]    105.0
3   1200000  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...    122.0
4         0  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...    118.0
5   8000000  [{'id': 16, 'name': 'Animation'}, {'id': 12, '...     83.0
6  14000000  [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...     92.0
7         0                [{'id': 99, 'name': 'Documentary'}]     84.0
8         0  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...    100.0
9   6000000  [{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...     91.0

In [50]:
# 2) iloc (indec locationig)
imdb_df.iloc[:5,3:4]
#here we see the first is rows and 5 is not included
#last is the index of colums in the dataframe, like column 1 column 2 column 3
#here also if we use 3:4 only 3 colum will b displayed
imdb_df.iloc[:5,3:5]
#see her we have column 3 and column 4

genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage  
0                                NaN  
1                                NaN  
2  http://sonyclassics.com/whiplash/  
3         http://kahaanithefilm.com/  
4                                NaN

In [53]:
# We can also do Boolean indexing
imdb_df.loc[:10,['Lang']] == 'en'

Lang
0    True
1    True
2    True
3   False
4   False
5    True
6    True
7    True
8    True
9    True
10   True

In [57]:
#Now we do one thing we create a new column using loc function
imdb_df.loc[:,'half_runtime'] = imdb_df.loc[:,'runtime'] * 0.5
imdb_df
#another method
imdb_df['half time new'] = imdb_df['runtime'] * 0.5
imdb_df
#both are correct

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id Lang  \
0                                   NaN  tt2637294   en   
1                                   NaN  tt0368933   en   
2     http://sonyclassics.com/whiplash/  tt2582802   en   
3            http://kahaanithefilm.com/  tt1821480   hi   
4                                   NaN  tt1380152   ko   
...                                 ...        ...  ...   
2995                                NaN  tt0109403   en   
2996                                NaN  tt2364975   sv   
2997                                NaN  tt0116908   en   
2998     http://www.alongcamepolly.com/  tt0343135   en   
2999   http://www.abductionthefilm.com/  tt1600195   en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

                                       spoken_languages    status  \
0              [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1              [{'iso_639_1': 'en', '

In [60]:
#Now new column by add sub mult dive two columns
imdb_df['movie_profit'] = imdb_df['revenue'] - imdb_df['budget']
imdb_df
#lets see can we add two string columns
imdb_df['movie_new_status'] = imdb_df['status'] - imdb_df['Lang']
#error two strings cannot be added only numeric values


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [69]:
imdb_df['movie_profit'].head(2)
imdb_df.sort_values('movie_profit', ascending = False).head(1)

id                              belongs_to_collection     budget  \
1761  1762  [{'id': 9485, 'name': 'The Fast and the Furiou...  190000000   

                              genres                  homepage    imdb_id  \
1761  [{'id': 28, 'name': 'Action'}]  http://www.furious7.com/  tt2820852   

     Lang original_title                                           overview  \
1761   en      Furious 7  Deckard Shaw seeks revenge against Dominic Tor...   

      popularity  ...    status              tagline      title  \
1761   27.275687  ...  Released  Vengeance Hits Home  Furious 7   

                                               Keywords  \
1761  [{'id': 830, 'name': 'car race'}, {'id': 3428,...   

                                                   cast  \
1761  [{'cast_id': 17, 'character': 'Dominic Toretto...   

                                                   crew     revenue  \
1761  [{'credit_id': '52fe4cc8c3a36847f823e681', 'de...  1506249360   

     half_runtime half time new movie_profit  
1761         68.5          68.5   1316249360  

[1 rows x 26 columns]

In [71]:
#remove columns
imdb_df.drop(['budget'], axis = 1)
# here axis 1 meand the column 0 mean the row also in place can be used to show change in the original data frame

id                              belongs_to_collection  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...   
2        3                                                NaN   
3        4                                                NaN   
4        5                                                NaN   
...    ...                                                ...   
2995  2996                                                NaN   
2996  2997                                                NaN   
2997  2998                                                NaN   
2998  2999                                                NaN   
2999  3000                                                NaN   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id Lang  \
0                                   NaN  tt2637294   en   
1                                   NaN  tt0368933   en   
2     http://sonyclassics.com/whiplash/  tt2582802   en   
3            http://kahaanithefilm.com/  tt1821480   hi   
4                                   NaN  tt1380152   ko   
...                                 ...        ...  ...   
2995                                NaN  tt0109403   en   
2996                                NaN  tt2364975   sv   
2997                                NaN  tt0116908   en   
2998     http://www.alongcamepolly.com/  tt0343135   en   
2999   http://www.abductionthefilm.com/  tt1600195   en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  \
0     When Lou, who has become the "father of the In...    6.575393   
1     Mia Thermopolis is now a college graduate and ...    8.248895   
2     Under the direction of a ruthless instructor, ...   64.299990   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936   
4     Marine Boy is the story of a former national s...    1.148070   
...                                                 ...         ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542   
2999  A young man sets out to uncover the truth abou...   10.512109   

                           poster_path  ...    status  \
0     /tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg  ...  Released   
1     /w9Z7A0GHEhIp7etpj0vyKOeU1Wx.jpg  ...  Released   
2     /lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg  ...  Released   
3     /aTXRaPrWSinhcmCrcfJK17urp3F.jpg  ...  Released   
4     /m22s7zvkVFDU9ir56PiiqIEWFdT.jpg  ...  Released   
...          

In [73]:
imdb_df.head()

id                              belongs_to_collection    budget  \
0   1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1   2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2   3                                                NaN   3300000   
3   4                                                NaN   1200000   
4   5                                                NaN         0   

                                              genres  \
0                     [{'id': 35, 'name': 'Comedy'}]   
1  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                      [{'id': 18, 'name': 'Drama'}]   
3  [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4  [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   

                            homepage    imdb_id Lang  \
0                                NaN  tt2637294   en   
1                                NaN  tt0368933   en   
2  http://sonyclassics.com/whiplash/  tt2582802   en   
3         http://kahaanithefilm.com/  tt1821480   hi   
4                                NaN  tt1380152   ko   

                             original_title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                      마린보이   

                                            overview  popularity  ...  \
0  When Lou, who has become the "father of the In...    6.575393  ...   
1  Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2  Under the direction of a ruthless instructor, ...   64.299990  ...   
3  Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4  Marine Boy is the story of a former national s...    1.148070  ...   

     status                                            tagline  \
0  Released  The Laws of Space and Time are About to be Vio...   
1  Released  It can take a lifetime to find true love; she'...   
2  Released    The road to greatness can take you to the edge.   
3  Released                                                NaN   
4  Released                                                NaN   

                                      title  \
0                    Hot Tub Time Machine 2   
1  The Princess Diaries 2: Royal Engagement   
2                                  Whiplash   
3                                   Kahaani   
4                                Marine Boy   

                                            Keywords  \
0  [{'id': 4379, 'name': 'time travel'}, {'id': 9...   
1  [{'id': 2505, 'name': 'coronation'}, {'id': 42...   
2  [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...   
3  [{'id': 10092, 'name': 'mystery'}, {'id': 1054...   
4                                                NaN   

                                                cast  \
0  [{'cast_id': 4, 'character': 'Lou', 'credit_id...   
1  [{'cast_id': 1, 'character': 'Mia Thermopolis'...   
2  [{'cast_id': 5, 'character': 'Andrew Neimann',...   
3  [{'cast_id': 1, 'character': 'Vidya Bagchi', '...   
4  [{'cast_id': 3, 'character': 'Chun-soo', 'cred...   

                                                crew   revenue half_runtime  \
0  [{'credit_id': '59ac067c92514107af02c8c8', 'de...  12314651         46.5   
1  [{'credit_id': '52fe43fe9251416c7502563d', 'de...  95149435         56.5   
2  [{'credit_id': '54d5356ec3a3683ba0000039', 'de...  13092000         52.5   
3  [{'credit_id': '52fe48779251416c9108d6eb', 'de...  16000000         61.0   
4  [{'credit_id': '52fe464b9251416c75073b43', 'de...   3923970         59.0   

  half time new movie_profit  
0          46.5     -1685349  
1          56.5     55149435  
2          52.5      9792000  
3          61.0     14800000  
4          59.0      3923970  

[5 rows x 26 columns]

In [87]:
high_rev = imdb_df.sort_values('revenue', ascending = False).head(5)['popularity']
#print(high_rev)
print("Movies with highest revenue\n",high_rev 'title','popularity','runtime')
low_rev = imdb_df.sort_values('revenue', ascending = True).head()['popularity']
#print(low_rev)

SyntaxError: invalid syntax (<ipython-input-87-746e21efaa4e>, line 3)

In [90]:
high_rev = imdb_df.sort_values('revenue', ascending=False).head(5)[['title', 'popularity', 'runtime']]
low_bud = imdb_df.sort_values('budget', ascending=True).head(5)[['title', 'popularity', 'runtime']]

print("Movies with highest revenue:\n", high_rev)
print("\nMovies with lowest budget:\n", low_bud)


Movies with highest revenue:
                                title  popularity  runtime
1126                    The Avengers   89.887648    143.0
1761                       Furious 7   27.275687    137.0
2770         Avengers: Age of Ultron   37.379420    141.0
684             Beauty and the Beast  287.253654    129.0
2322  Transformers: Dark of the Moon    4.503505    154.0

Movies with lowest budget:
                            title  popularity  runtime
895               Gray Lady Down    3.507084    111.0
594                    Tommy Boy   11.971318     97.0
595   A Prince (almost) Charming    1.985348     88.0
1252         Murder in the First    9.518564    122.0
2144               The Final Cut    1.797462     96.0


In [106]:
eng = imdb_df[imdb_df['Lang'] == 'en']
hin = imdb_df[imdb_df['Lang'] == 'hi']
eng.sort_values('runtime', ascending = False).head()


id belongs_to_collection    budget  \
1211  1212                   NaN  18000000   
1922  1923                   NaN  31115000   
523    524                   NaN  13000000   
1302  1303                   NaN  44000000   
1914  1915                   NaN  56000000   

                                                 genres homepage    imdb_id  \
1211  [{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...      NaN  tt1321865   
1922  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...      NaN  tt0056937   
523   [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...      NaN  tt0049833   
1302  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...      NaN  tt0080855   
1914  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...      NaN  tt0279111   

     Lang        original_title  \
1211   en                Carlos   
1922   en             Cleopatra   
523    en  The Ten Commandments   
1302   en         Heaven's Gate   
1914   en     Gods and Generals   

                                               overview  popularity  ...  \
1211  The story of Venezuelan revolutionary, Ilich R...    4.558075  ...   
1922  Historical epic. The triumphs and tragedy of t...    8.591238  ...   
523   Escaping death, a Hebrew infant is raised in a...   11.147040  ...   
1302  Harvard graduate James Averill (Kris Kristoffe...    4.393576  ...   
1914  The film centers mostly around the personal an...    5.374563  ...   

        status                                            tagline  \
1211  Released                     The man who hijacked the world   
1922  Released  The motion picture the world has been waiting ...   
523   Released                                                NaN   
1302  Released  The only thing greater than their passion for ...   
1914  Released                The nations heart was touched by...   

                     title                                           Keywords  \
1211                Carlos  [{'id': 1419, 'name': 'gun'}, {'id': 7336, 'na...   
1922             Cleopatra  [{'id': 5049, 'name': 'ancient rome'}, {'id': ...   
523   The Ten Commandments  [{'id': 1160, 'name': 'egypt'}, {'id': 2618, '...   
1302         Heaven's Gate  [{'id': 680, 'name': 'montana'}, {'id': 797, '...   
1914     Gods and Generals  [{'id': 6091, 'name': 'war'}, {'id': 14643, 'n...   

                                                   cast  \
1211  [{'cast_id': 4, 'character': "Ilich Ramírez S...   
1922  [{'cast_id': 2, 'character': 'Cleopatra', 'cre...   
523   [{'cast_id': 9, 'character': 'Moses', 'credit_...   
1302  [{'cast_id': 1, 'character': 'James Averill', ...   
1914  [{'cast_id': 3, 'character': 'Lt. Gen. Thomas ...   

                                                   crew    revenue  \
1211  [{'credit_id': '57352b61c3a3680253000870', 'de...     871279   
1922  [{'credit_id': '52fe4493c3a36847f809de91', 'de...   71000000   
523   [{'credit_id': '58acab8cc3a3686f0d00093f', 'de...  122700000   
1302  [{'credit_id': '52fe43d49251416c7501fcf7', 'de...    3484331   
1914  [{'credit_id': '52fe469e9251416c7507dfbb', 'de...   12923936   

     half_runtime half time new movie_profit  
1211        169.0         169.0    -17128721  
1922        124.0         124.0     39885000  
523         110.0         110.0    109700000  
1302        109.5         109.5    -40515669  
1914        107.0         107.0    -43076064  

[5 rows x 26 columns]

In [107]:
eng.sort_values('runtime', ascending = False).head()
hin.sort_values('runtime', ascending = False).head()

id belongs_to_collection   budget  \
2353  2354                   NaN  8376800   
2563  2564                   NaN  7400000   
1987  1988                   NaN        0   
1640  1641                   NaN  4600000   
1572  1573                   NaN  9100000   

                                                 genres  \
2353  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...   
2563  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...   
1987  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
1640  [{'id': 36, 'name': 'History'}, {'id': 28, 'na...   
1572  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                             homepage    imdb_id Lang      original_title  \
2353      http://www.jodhaaakbar.com/  tt0449994   hi        Jodhaa Akbar   
2563                              NaN  tt0449999   hi  कभी अलविदा ना कहना   
1987                              NaN  tt0347304   hi         कल हो ना हो   
1640                              NaN  tt2356180   hi  Bhaag Milkha Bhaag   
1572  http://www.rememberghajini.com/  tt1166100   hi             Ghajini   

                                               overview  popularity  ...  \
2353  Jodhaa Akbar is a sixteenth century love story...   12.237488  ...   
2563  Dev and Maya are both married to different peo...    2.372520  ...   
1987  Naina is a very serious girl with a very serio...    5.584308  ...   
1640  The true story of the "Flying Sikh" world cham...    4.342418  ...   
1572  Sanjay a rich tycoon suffering from short term...    4.239080  ...   

        status                                  tagline  \
2353  Released                                      NaN   
2563  Released  A Love.... That Broke All Relationships   
1987  Released                                      NaN   
1640  Released         Now you will see his Real Story.   
1572  Released                                      NaN   

                       title  \
2353            Jodhaa Akbar   
2563  Kabhi Alvida Naa Kehna   
1987           Kal Ho Naa Ho   
1640      Bhaag Milkha Bhaag   
1572                 Ghajini   

                                               Keywords  \
2353  [{'id': 1157, 'name': 'wife husband relationsh...   
2563  [{'id': 596, 'name': 'adultery'}, {'id': 34094...   
1987  [{'id': 242, 'name': 'new york'}, {'id': 958, ...   
1640  [{'id': 795, 'name': 'running'}, {'id': 1721, ...   
1572  [{'id': 331, 'name': 'tattoo'}, {'id': 154785,...   

                                                   cast  \
2353  [{'cast_id': 1, 'character': 'Jalaluddin Moham...   
2563  [{'cast_id': 1, 'character': 'Dev Saran', 'cre...   
1987  [{'cast_id': 8, 'character': 'Aman Mathur', 'c...   
1640  [{'cast_id': 1, 'character': 'Milkha Singh', '...   
1572  [{'cast_id': 12, 'character': 'Sanjay Singhani...   

                                                   crew   revenue  \
2353  [{'credit_id': '52fe45c99251416c75062761', 'de...  13000000   
2563  [{'credit_id': '52fe45ee9251416c75067637', 'de...  17000000   
1987  [{'credit_id': '52fe43b6c3a36847f8069c57', 'de...  13200241   
1640  [{'credit_id': '52fe4d1ac3a368484e1d74af', 'de...  25000000   
1572  [{'credit_id': '52fe45c99251416c75062659', 'de...  76000000   

     half_runtime half time new movie_profit  
2353        106.5         106.5      4623200  
2563         96.5          96.5      9600000  
1987         93.0          93.0     13200241  
1640         93.0          93.0     20400000  
1572         91.5          91.5     66900000  

[5 rows x 26 columns]

In [119]:
print(imdb_df['runtime'])
new = imdb_df['new_colum_time'] = imdb_df['runtime'] + 10
new


0        93.0
1       113.0
2       105.0
3       122.0
4       118.0
        ...  
2995    102.0
2996    102.0
2997    120.0
2998     90.0
2999    106.0
Name: runtime, Length: 3000, dtype: float64


0       103.0
1       123.0
2       115.0
3       132.0
4       128.0
        ...  
2995    112.0
2996    112.0
2997    130.0
2998    100.0
2999    116.0
Name: runtime, Length: 3000, dtype: float64

In [120]:
imdb_df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id Lang  \
0                                   NaN  tt2637294   en   
1                                   NaN  tt0368933   en   
2     http://sonyclassics.com/whiplash/  tt2582802   en   
3            http://kahaanithefilm.com/  tt1821480   hi   
4                                   NaN  tt1380152   ko   
...                                 ...        ...  ...   
2995                                NaN  tt0109403   en   
2996                                NaN  tt2364975   sv   
2997                                NaN  tt0116908   en   
2998     http://www.alongcamepolly.com/  tt0343135   en   
2999   http://www.abductionthefilm.com/  tt1600195   en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

                                                tagline  \
0     The Laws of Space and Time are About to be Vio...   
1     It can take a lifetime to find true love; she'...  