<a href="https://colab.research.google.com/github/azameap/Python/blob/main/Pandas_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np
import pandas as pd


In [6]:
#Crete a numpy array
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [7]:
#create a pandas dataframe
data_frame = pd.DataFrame({'Name:':['A','B','C'], 'Age: ':[1,2,3]})
data_frame

Name:  Age: 
0     A      1
1     B      2
2     C      3

In [22]:
#Create array of random integers
arr= np.random.randint(0,100, size=10)
arr

array([22, 39, 62, 82, 46, 60, 64, 78, 17, 28])

In [17]:
#sort array in ascending order
arr_sort = np.sort(arr)


array([ 2,  6, 11, 13, 15, 23, 27, 29, 33, 51])

In [26]:
#One Dimensional array
arr = np.array([1,2,3,4,5,6])
# lets pu an operation on it
# lets square it by 2
sqr_arr = arr**2
print(sqr_arr)

[ 1  4  9 16 25 36]


In [28]:
# Here we see in one go we are able to apply the operation to teh rest of the elements in the array
#Similarly
sum_arr = np.sum(arr) # like this add all the elements in the array
print(sum_arr)

21


In [30]:
#Similarly, we use mean to find the mean of the elements
mean_arr = np.mean(arr)
mean_arr

3.5

In [40]:
#Why is Numpy important in data Analysis?
#1 we can make oneD or 2D or any Dimention arrays in Numpy
#Example of one d is above, lets make 2D array
arr_2d = np.array([[1,2,3],[4,10,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
#2 Numpy Mean
#It is a statistical method, Provides measure of the central tendancy of a dataset
mean_arr_2d = np.mean(arr_2d)
mean_arr_2d

5.555555555555555

In [41]:
#Numpy Meadian, This is also for central tendancy
median_arr_2d = np.median(arr_2d)
median_arr_2d

5.0

In [45]:
#numpy std;calculate standard deviation of an array
#measure of spread or variability of a dataset
std_arr_2d = np.std(arr_2d)
std_arr_2d

2.581988897471611

In [47]:
#lets do it simple
arr = np.array([1,2,3,4,5])
np.std(arr)

1.4142135623730951

In [ ]:
#Numpy functionality
#1 Numpy Array
#Howw? np.array([1,2,3])


In [50]:
#2 is Numpy arange
#used to create an array with evenly spaced values within a specified range
#takes 3 arguments start stop step
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.arange(5,10,2)
arr

array([5, 7, 9])

In [57]:
#Numpy Linespace
#Evenly spaced values within a specified range, start stop num
arr = np.linspace(0,1,100)
arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [58]:
#Numpy reshape: used to change the shap eof an array
#for example we make an array using arange function in numpy
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#the above array is a one dimentional array and we want to change the shape and turn into a 2 dimentional array
arr_2d = arr.reshape(2,5)
arr_2d
#Here we have a 5x2 matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
#Numpy tranpose, you might have used this term while studying matrix
#what is a transpose?
#it simply means swapping rows and columns
new_arr = np.transpose(arr_2d)
new_arr
#here we get a 2x5 matrix

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [70]:
#Flatten is a method to convert multi dimentional array into a one dimentional array
arr_2d
new_arr = arr_2d.flatten()
new_arr
print(f'''Orginal array: {arr_2d} and new array {new_arr}''')

Orginal array: [[0 1 2 3 4]
 [5 6 7 8 9]] and new array [0 1 2 3 4 5 6 7 8 9]


In [72]:
#Indexing and slicing a numpy array
#extracting a subset of numpy array
#lets make a 3 dimentional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
#Slice first matrix of array
matrix_1 = arr[0,::]
matrix_1

array([1, 2, 3])

In [87]:
arr[]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed